# Generated by Django 2.0.7 on 2018-07-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='l_name',
            field=models.CharField(default='ali', max_length=100),
            preserve_default=False,
        ),
    ]
