# Generated by Django 2.0.7 on 2018-07-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_person_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='m_name',
            field=models.CharField(default='middle name ', max_length=100),
            preserve_default=False,
        ),
    ]
