# Generated by Django 2.0.7 on 2018-07-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_person_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='f_name',
            field=models.CharField(blank='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='m_name',
            field=models.CharField(blank='true', max_length=100),
        ),
    ]
