# Generated by Django 2.0.7 on 2018-07-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='angy size', max_length=1),
            preserve_default=False,
        ),
    ]
